USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'MARFARMA_DB')
BEGIN
    ALTER DATABASE MARFARMA_DB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE MARFARMA_DB;
END
GO

CREATE DATABASE MARFARMA_DB;
GO

USE MARFARMA_DB;
GO
